import { Cocktail } from './types';

export const cocktails: Cocktail[] = [
  {
    id: 'mojito',
    name: '莫吉托',
    nameEn: 'Mojito',
    baseSpirit: '朗姆酒',
    difficulty: 2,
    abv: 10,
    color: '#27ae60',
    flavor: '清新薄荷与青柠的完美融合，微甜微酸，夏日经典消暑饮品。',
    description: '莫吉托起源于古巴，是最受欢迎的鸡尾酒之一。清新的薄荷叶与青柠汁搭配白朗姆酒，加上苏打水的气泡感，是炎炎夏日的绝佳选择。',
    ingredients: [
      { name: '白朗姆酒', amount: '45ml' },
      { name: '新鲜薄荷叶', amount: '8-10片' },
      { name: '青柠', amount: '半个' },
      { name: '白砂糖', amount: '2茶匙' },
      { name: '苏打水', amount: '适量' },
      { name: '碎冰', amount: '满杯' },
    ],
    steps: [
      '将薄荷叶放入杯中，加入白砂糖和青柠汁。',
      '用吧勺轻轻捣压薄荷叶，释放香气（注意不要捣碎）。',
      '加入碎冰至杯口。',
      '倒入白朗姆酒，搅拌均匀。',
      '注入苏打水至满杯，轻轻搅拌。',
      '用薄荷枝和青柠角装饰即可。',
    ],
    tips: '薄荷叶只需轻轻按压，过度捣压会释放苦味。建议使用新鲜薄荷，干燥薄荷无法达到同样的效果。杯子提前冰镇口感更佳。',
  },
  {
    id: 'daiquiri',
    name: '大吉利',
    nameEn: 'Daiquiri',
    baseSpirit: '朗姆酒',
    difficulty: 2,
    abv: 14,
    color: '#f1c40f',
    flavor: '酸甜平衡的经典之作，青柠的酸爽与朗姆酒的甘甜交织。',
    description: '大吉利是一款以朗姆酒为基酒的经典鸡尾酒，诞生于古巴的达伊基里矿区。简单的三种原料创造出令人惊叹的平衡口感。',
    ingredients: [
      { name: '白朗姆酒', amount: '60ml' },
      { name: '新鲜青柠汁', amount: '30ml' },
      { name: '单糖浆', amount: '15ml' },
    ],
    steps: [
      '将所有材料倒入雪克杯中。',
      '加入大量冰块，用力摇晃15秒。',
      '滤入冰镇的鸡尾酒杯中。',
      '用青柠轮装饰杯口。',
    ],
    tips: '这款酒的灵魂在于酸甜比例的精准把控。务必使用新鲜榨取的青柠汁，瓶装浓缩汁会破坏口感。',
  },
  {
    id: 'pina-colada',
    name: '椰林飘香',
    nameEn: 'Pina Colada',
    baseSpirit: '朗姆酒',
    difficulty: 2,
    abv: 13,
    color: '#fdebd0',
    flavor: '热带风情的浓郁椰香与菠萝的甜蜜，仿佛置身海滩度假。',
    description: '椰林飘香是波多黎各的国民鸡尾酒，1978年被定为波多黎各官方饮品。椰奶的丝滑与菠萝的酸甜完美融合。',
    ingredients: [
      { name: '白朗姆酒', amount: '45ml' },
      { name: '椰浆', amount: '45ml' },
      { name: '菠萝汁', amount: '90ml' },
      { name: '碎冰', amount: '1杯' },
      { name: '菠萝角', amount: '装饰用' },
    ],
    steps: [
      '将朗姆酒、椰浆、菠萝汁和碎冰放入搅拌机。',
      '高速搅拌至顺滑细腻。',
      '倒入飓风杯或大肚杯中。',
      '用菠萝角和樱桃装饰。',
    ],
    tips: '椰浆建议使用罐装浓椰浆而非椰奶饮料，口感更加浓郁。可以根据个人喜好调整冰量来控制浓稠度。',
  },
  {
    id: 'dark-n-stormy',
    name: '黑暗风暴',
    nameEn: 'Dark & Stormy',
    baseSpirit: '朗姆酒',
    difficulty: 1,
    abv: 10,
    color: '#784212',
    flavor: '深色朗姆酒的焦糖风味与姜汁啤酒的辛辣完美碰撞。',
    description: '黑暗风暴诞生于百慕大，是当地海军军官的最爱。深色朗姆酒缓缓倒入姜汁啤酒中，形成如暴风雨般的云层效果。',
    ingredients: [
      { name: '黑朗姆酒', amount: '60ml' },
      { name: '姜汁啤酒', amount: '120ml' },
      { name: '青柠角', amount: '装饰用' },
    ],
    steps: [
      '在高球杯中装满冰块。',
      '倒入姜汁啤酒至七分满。',
      '缓缓注入黑朗姆酒，使其漂浮在上层。',
      '用青柠角装饰，饮用前轻轻搅拌。',
    ],
    tips: '朗姆酒一定要最后倒入，这样可以在上层形成美丽的渐变色。姜汁啤酒比姜汁汽水更辛辣，风味更佳。',
  },
  {
    id: 'moscow-mule',
    name: '莫斯科骡子',
    nameEn: 'Moscow Mule',
    baseSpirit: '伏特加',
    difficulty: 1,
    abv: 10,
    color: '#bdc3c7',
    flavor: '伏特加的纯净与姜汁啤酒的辛辣，青柠增添清新酸度。',
    description: '莫斯科骡子是1940年代美国伏特加商人与姜汁啤酒品牌联合推广的杰作。传统上使用铜杯盛装，铜的导热性让饮品始终冰凉。',
    ingredients: [
      { name: '伏特加', amount: '45ml' },
      { name: '姜汁啤酒', amount: '120ml' },
      { name: '新鲜青柠汁', amount: '15ml' },
      { name: '青柠角', amount: '装饰用' },
    ],
    steps: [
      '在铜杯或高球杯中装满冰块。',
      '倒入伏特加和新鲜青柠汁。',
      '注入姜汁啤酒至满杯。',
      '轻轻搅拌，用青柠角和薄荷枝装饰。',
    ],
    tips: '铜杯不仅是为了好看，铜的温度传导可以让饮品保持冰爽。如果使用铜杯，请确认杯内壁有食品级涂层。',
  },
  {
    id: 'cosmopolitan',
    name: '大都会',
    nameEn: 'Cosmopolitan',
    baseSpirit: '伏特加',
    difficulty: 2,
    abv: 20,
    color: '#e74c3c',
    flavor: '蔓越莓的酸甜与柑橘利口酒的芬芳，优雅迷人的粉色佳酿。',
    description: '大都会因电视剧《欲望都市》而风靡全球，是都市时尚女性的标志性饮品。粉红色的外观和优雅的口感使其成为派对宠儿。',
    ingredients: [
      { name: '伏特加', amount: '40ml' },
      { name: '柑曼怡利口酒', amount: '15ml' },
      { name: '蔓越莓汁', amount: '30ml' },
      { name: '新鲜青柠汁', amount: '15ml' },
    ],
    steps: [
      '提前冰镇马天尼杯。',
      '将所有材料倒入装满冰的雪克杯中。',
      '用力摇晃12-15秒直至杯壁结霜。',
      '双重过滤倒入马天尼杯。',
      '用柠檬皮卷或橙皮装饰。',
    ],
    tips: '蔓越莓汁选择原味而非甜味的，否则成品会过甜。摇晃时间要足够长，确保充分冷却和稀释。',
  },
  {
    id: 'bloody-mary',
    name: '血腥玛丽',
    nameEn: 'Bloody Mary',
    baseSpirit: '伏特加',
    difficulty: 3,
    abv: 10,
    color: '#c0392b',
    flavor: '番茄汁的鲜美与多种香料的复杂层次，咸鲜微辣的开胃圣品。',
    description: '血腥玛丽是最经典的早午餐鸡尾酒，据说以英格兰女王"血腥玛丽"命名。丰富的调味让每一口都充满层次感。',
    ingredients: [
      { name: '伏特加', amount: '45ml' },
      { name: '番茄汁', amount: '90ml' },
      { name: '新鲜柠檬汁', amount: '15ml' },
      { name: '伍斯特酱', amount: '2-3滴' },
      { name: '塔巴斯科辣酱', amount: '适量' },
      { name: '芹菜盐', amount: '少许' },
      { name: '黑胡椒', amount: '少许' },
      { name: '芹菜梗', amount: '1根（装饰）' },
    ],
    steps: [
      '在高球杯的杯口用柠檬角擦一圈，蘸上芹菜盐。',
      '在杯中装入冰块。',
      '倒入伏特加和柠檬汁。',
      '加入番茄汁和伍斯特酱。',
      '滴入塔巴斯科辣酱（按个人口味调整）。',
      '轻轻搅拌均匀，撒上黑胡椒。',
      '插入芹菜梗作为装饰和搅拌棒。',
    ],
    tips: '辣度完全可以自定义。如果喜欢更辣，可以加入少许辣根或芥末。这是一款非常适合宿醉第二天的鸡尾酒。',
  },
  {
    id: 'vodka-martini',
    name: '伏特加马天尼',
    nameEn: 'Vodka Martini',
    baseSpirit: '伏特加',
    difficulty: 2,
    abv: 30,
    color: '#ecf0f1',
    flavor: '极致纯净的口感，微苦的味美思平衡伏特加的辛辣。',
    description: '这是007詹姆斯·邦德的经典之选——"摇晃，不要搅拌"。纯净而强烈的口感，是考验调酒师基本功的经典之作。',
    ingredients: [
      { name: '伏特加', amount: '60ml' },
      { name: '干味美思', amount: '10ml' },
      { name: '橄榄', amount: '装饰用' },
    ],
    steps: [
      '提前冰镇马天尼杯。',
      '将伏特加和干味美思倒入雪克杯中。',
      '加入冰块，摇晃或搅拌至充分冷却。',
      '双重过滤倒入冰镇的马天尼杯。',
      '用橄榄或柠檬皮装饰。',
    ],
    tips: '传统马天尼是搅拌而非摇晃的，摇晃会让酒体变得浑浊（邦德的偏好）。味美思的用量可以按个人喜好调整。',
  },
  {
    id: 'sex-on-the-beach',
    name: '海滩激情',
    nameEn: 'Sex on the Beach',
    baseSpirit: '伏特加',
    difficulty: 1,
    abv: 10,
    color: '#ff6b6b',
    flavor: '桃子的甜美与蔓越莓的酸爽交织，热带水果风味的派对佳酿。',
    description: '这款鸡尾酒诞生于1980年代的佛罗里达，名字虽然大胆，但口感温柔甜蜜，是度假风格的经典饮品。',
    ingredients: [
      { name: '伏特加', amount: '40ml' },
      { name: '桃子利口酒', amount: '20ml' },
      { name: '鲜橙汁', amount: '40ml' },
      { name: '蔓越莓汁', amount: '40ml' },
      { name: '橙片', amount: '装饰用' },
    ],
    steps: [
      '在高球杯中装满冰块。',
      '倒入伏特加和桃子利口酒。',
      '加入鲜橙汁。',
      '最后注入蔓越莓汁，形成渐变效果。',
      '用橙片和樱桃装饰。',
    ],
    tips: '蔓越莓汁最后倒入可以形成美丽的日落渐变效果。如果追求更甜的口感，可以增加桃子利口酒的比例。',
  },
  {
    id: 'old-fashioned',
    name: '古典鸡尾酒',
    nameEn: 'Old Fashioned',
    baseSpirit: '威士忌',
    difficulty: 2,
    abv: 32,
    color: '#d4a24e',
    flavor: '威士忌的醇厚与苦精的复杂香气，方糖带来圆润甜感。',
    description: '古典鸡尾酒被认为是所有鸡尾酒的鼻祖，名称来源于点酒时"老式做法"的要求。简单却极考验功夫的经典。',
    ingredients: [
      { name: '波本威士忌', amount: '60ml' },
      { name: '安格仕苦精', amount: '2-3滴' },
      { name: '方糖', amount: '1块' },
      { name: '水', amount: '少许' },
      { name: '橙皮', amount: '1片' },
      { name: '樱桃', amount: '1颗' },
    ],
    steps: [
      '将方糖放入古典杯底部。',
      '滴上苦精，加少许水，用吧勺碾碎方糖。',
      '加入一大块冰球或方冰。',
      '倒入波本威士忌，轻轻搅拌约20圈。',
      '用橙皮在杯口挤出油脂，擦拭杯口后放入杯中。',
      '放入樱桃装饰。',
    ],
    tips: '使用大冰块可以减缓融化速度，避免过度稀释。橙皮要挤压释放油脂，这是风味的关键来源。',
  },
  {
    id: 'whiskey-sour',
    name: '威士忌酸酒',
    nameEn: 'Whiskey Sour',
    baseSpirit: '威士忌',
    difficulty: 2,
    abv: 14,
    color: '#f0b429',
    flavor: '酸甜适口的经典酸酒，柠檬的清新与波本的温暖完美交融。',
    description: '威士忌酸酒是酸酒家族的代表作，将烈酒与柠檬汁、糖浆的黄金比例演绎到极致。加入蛋清可以创造丝滑口感。',
    ingredients: [
      { name: '波本威士忌', amount: '45ml' },
      { name: '新鲜柠檬汁', amount: '25ml' },
      { name: '单糖浆', amount: '15ml' },
      { name: '蛋清', amount: '可选，1个' },
      { name: '樱桃', amount: '装饰用' },
    ],
    steps: [
      '如使用蛋清，先将蛋清倒入雪克杯中，不加冰干摇10秒。',
      '加入威士忌、柠檬汁和糖浆。',
      '加入冰块，用力摇晃15-20秒。',
      '双重过滤倒入古典杯中。',
      '在泡沫上滴几滴苦精，用牙签画出花纹。',
      '用樱桃装饰。',
    ],
    tips: '蛋清是可选的，但加入后会创造出令人惊叹的丝滑泡沫层。干摇（不加冰先摇）是让蛋清充分起泡的关键。',
  },
  {
    id: 'mint-julep',
    name: '薄荷朱利普',
    nameEn: 'Mint Julep',
    baseSpirit: '威士忌',
    difficulty: 2,
    abv: 20,
    color: '#82e0aa',
    flavor: '清凉薄荷与波本威士忌的甘甜交融，美国南方的经典风味。',
    description: '薄荷朱利普是美国肯塔基州赛马会的官方饮品，自1938年以来每年赛马日售出近12万杯。银杯盛装是传统。',
    ingredients: [
      { name: '波本威士忌', amount: '60ml' },
      { name: '新鲜薄荷叶', amount: '8-10片' },
      { name: '单糖浆', amount: '15ml' },
      { name: '碎冰', amount: '满杯' },
    ],
    steps: [
      '将薄荷叶和糖浆放入朱利普杯或高球杯中。',
      '轻轻捣压薄荷叶，释放香气。',
      '加入碎冰至杯口。',
      '倒入波本威士忌。',
      '用吧勺从底部向上搅拌，使杯壁起霜。',
      '再补满碎冰，用薄荷枝装饰。',
    ],
    tips: '银杯或金属杯可以让碎冰保持更久。薄荷枝在手中拍打几下再放入杯中，可以更好地释放香气。',
  },
  {
    id: 'manhattan',
    name: '曼哈顿',
    nameEn: 'Manhattan',
    baseSpirit: '威士忌',
    difficulty: 3,
    abv: 30,
    color: '#8b4513',
    flavor: '黑麦威士忌的辛辣与甜味美思的醇厚，苦精增添复杂层次。',
    description: '曼哈顿是鸡尾酒中的贵族，据说诞生于1870年代纽约曼哈顿俱乐部。深琥珀色的酒体散发着成熟稳重的魅力。',
    ingredients: [
      { name: '黑麦威士忌', amount: '60ml' },
      { name: '甜味美思', amount: '30ml' },
      { name: '安格仕苦精', amount: '2-3滴' },
      { name: '樱桃', amount: '装饰用' },
    ],
    steps: [
      '提前冰镇马天尼杯。',
      '将威士忌、甜味美思和苦精倒入搅拌杯中。',
      '加入冰块，用吧勺轻轻搅拌约30圈。',
      '双重过滤倒入冰镇的马天尼杯中。',
      '用鸡尾酒樱桃装饰。',
    ],
    tips: '曼哈顿适合搅拌而非摇晃，搅拌可以保持酒体的清澈和丝滑质感。甜味美思开封后要冷藏保存，一个月内用完最佳。',
  },
  {
    id: 'irish-coffee',
    name: '爱尔兰咖啡',
    nameEn: 'Irish Coffee',
    baseSpirit: '威士忌',
    difficulty: 3,
    abv: 14,
    color: '#6d4c41',
    flavor: '热咖啡的醇苦与爱尔兰威士忌的温暖，奶油的丝滑收尾。',
    description: '爱尔兰咖啡据说在1940年代由爱尔兰一家机场餐厅发明，目的是为寒冷的旅客暖身。它既是咖啡也是鸡尾酒。',
    ingredients: [
      { name: '爱尔兰威士忌', amount: '40ml' },
      { name: '热咖啡', amount: '150ml' },
      { name: '红糖', amount: '2茶匙' },
      { name: '鲜奶油', amount: '适量' },
    ],
    steps: [
      '用热水预热爱尔兰咖啡杯。',
      '倒入红糖和少许热咖啡，搅拌至糖溶化。',
      '加入爱尔兰威士忌，搅拌均匀。',
      '倒入热咖啡至八分满。',
      '将打至半发的鲜奶油缓缓倒在汤匙背面，漂浮在咖啡上方。',
      '不要搅拌，直接从奶油层下方饮用。',
    ],
    tips: '奶油要打到刚好可以流动的程度（不要打成全发），这样可以完美漂浮在咖啡上方。建议使用浅烘焙咖啡豆，不会抢威士忌的风头。',
  },
  {
    id: 'gin-tonic',
    name: '金汤力',
    nameEn: 'Gin & Tonic',
    baseSpirit: '金酒',
    difficulty: 1,
    abv: 10,
    color: '#abebc6',
    flavor: '杜松子的草本清香与汤力水的微苦气泡，清爽利落的经典搭配。',
    description: '金汤力起源于英国殖民印度时期，汤力水中的奎宁是预防疟疾的良药，金酒则是为了掩盖苦味。如今已是最受欢迎的简单鸡尾酒。',
    ingredients: [
      { name: '金酒', amount: '45ml' },
      { name: '汤力水', amount: '120ml' },
      { name: '青柠角', amount: '1个' },
      { name: '冰块', amount: '满杯' },
    ],
    steps: [
      '在高球杯或大肚杯中装满冰块。',
      '倒入金酒。',
      '缓缓注入冰镇的汤力水。',
      '轻轻搅拌一两下。',
      '挤入青柠汁，将青柠角放入杯中。',
    ],
    tips: '汤力水一定要冰镇的，气泡更充足。倒汤力水时沿杯壁缓缓倒入可以减少气泡散失。可以加入花椒、黄瓜等提升风味。',
  },
  {
    id: 'tom-collins',
    name: '汤姆柯林斯',
    nameEn: 'Tom Collins',
    baseSpirit: '金酒',
    difficulty: 2,
    abv: 10,
    color: '#d5f5e3',
    flavor: '金酒的草本风味与柠檬的清新酸度，苏打水的气泡带来轻盈口感。',
    description: '汤姆柯林斯有着一段有趣的传说——1874年纽约的一场恶作剧催生了这款酒。它是柯林斯家族中最经典的成员。',
    ingredients: [
      { name: '金酒', amount: '45ml' },
      { name: '新鲜柠檬汁', amount: '25ml' },
      { name: '单糖浆', amount: '15ml' },
      { name: '苏打水', amount: '适量' },
      { name: '樱桃和橙片', amount: '装饰用' },
    ],
    steps: [
      '将金酒、柠檬汁和糖浆倒入装满冰的柯林斯杯中。',
      '搅拌均匀。',
      '注入苏打水至满杯。',
      '轻轻搅拌，用樱桃和橙片装饰。',
    ],
    tips: '这是一款非常适合入门的金酒鸡尾酒。柠檬汁和糖浆的比例可以按个人酸甜偏好调整。',
  },
  {
    id: 'negroni',
    name: '尼格罗尼',
    nameEn: 'Negroni',
    baseSpirit: '金酒',
    difficulty: 2,
    abv: 24,
    color: '#e74c3c',
    flavor: '金酒的草本、金巴利的苦甜与甜味美思的醇厚，三者完美平衡。',
    description: '尼格罗尼诞生于1919年的意大利佛罗伦萨，由卡米洛·尼格罗尼伯爵要求调酒师在他的Americano中用金酒代替苏打水而得名。',
    ingredients: [
      { name: '金酒', amount: '30ml' },
      { name: '金巴利', amount: '30ml' },
      { name: '甜味美思', amount: '30ml' },
      { name: '橙皮', amount: '装饰用' },
    ],
    steps: [
      '提前冰镇古典杯。',
      '将三种材料倒入搅拌杯中。',
      '加入冰块，轻轻搅拌约30圈。',
      '倒入装有大冰块的古典杯中。',
      '用橙皮在杯口挤出油脂后放入杯中。',
    ],
    tips: '尼格罗尼的灵魂在于三种等份的平衡。如果觉得太苦，可以减少金巴利的量或增加甜味美思。橙皮的油脂是点睛之笔。',
  },
  {
    id: 'martinez',
    name: '马丁内斯',
    nameEn: 'Martinez',
    baseSpirit: '金酒',
    difficulty: 3,
    abv: 24,
    color: '#d4a24e',
    flavor: '老汤姆金酒的甜润与甜味美思的柔美，苦精增添深邃底蕴。',
    description: '马丁内斯被认为是马天尼的前身，诞生于19世纪中叶的美国加州马丁内斯镇。它是金酒鸡尾酒中被遗忘的经典。',
    ingredients: [
      { name: '老汤姆金酒', amount: '45ml' },
      { name: '甜味美思', amount: '45ml' },
      { name: '马拉斯奇诺利口酒', amount: '1茶匙' },
      { name: '橙味苦精', amount: '2滴' },
      { name: '樱桃', amount: '装饰用' },
    ],
    steps: [
      '提前冰镇马天尼杯。',
      '将所有材料倒入搅拌杯中。',
      '加入冰块，缓慢搅拌约30圈。',
      '双重过滤倒入冰镇马天尼杯。',
      '用鸡尾酒樱桃装饰。',
    ],
    tips: '传统上使用老汤姆金酒（略甜的金酒），如果使用伦敦干金酒，可适当增加利口酒的量来平衡。',
  },
  {
    id: 'margarita',
    name: '玛格丽特',
    nameEn: 'Margarita',
    baseSpirit: '龙舌兰',
    difficulty: 2,
    abv: 14,
    color: '#f9e79f',
    flavor: '龙舌兰的热情与青柠的清新酸度，盐边增添独特的咸鲜感。',
    description: '玛格丽特是世界上最受欢迎的龙舌兰鸡尾酒，盐边是其标志性的装饰。传说这是调酒师为纪念已故恋人而创作的。',
    ingredients: [
      { name: '龙舌兰', amount: '50ml' },
      { name: '君度利口酒', amount: '20ml' },
      { name: '新鲜青柠汁', amount: '25ml' },
      { name: '盐', amount: '杯边用' },
      { name: '青柠角', amount: '装饰用' },
    ],
    steps: [
      '用青柠角擦湿马天尼杯或古典杯的杯口。',
      '将杯口倒扣在盐碟上，形成盐边。',
      '将龙舌兰、君度和青柠汁倒入雪克杯。',
      '加入冰块，用力摇晃15秒。',
      '双重过滤倒入准备好的杯子中。',
      '用青柠角装饰。',
    ],
    tips: '只在杯口外侧擦盐，避免盐粒落入酒中影响口感。青柠汁一定要现榨的，瓶装青柠汁的味道差距明显。',
  },
  {
    id: 'tequila-sunrise',
    name: '龙舌兰日出',
    nameEn: 'Tequila Sunrise',
    baseSpirit: '龙舌兰',
    difficulty: 1,
    abv: 10,
    color: '#e67e22',
    flavor: '橙汁的甜蜜与石榴糖浆的渐变色彩，如同观赏日出般美好。',
    description: '龙舌兰日出因杯中橙红色渐变如日出而得名，1970年代在滚石乐队的巡演中走红。是最适合拍照的鸡尾酒之一。',
    ingredients: [
      { name: '龙舌兰', amount: '45ml' },
      { name: '鲜橙汁', amount: '90ml' },
      { name: '红石榴糖浆', amount: '15ml' },
      { name: '橙片', amount: '装饰用' },
      { name: '樱桃', amount: '装饰用' },
    ],
    steps: [
      '在高球杯中装满冰块。',
      '倒入龙舌兰。',
      '注入鲜橙汁，搅拌均匀。',
      '沿杯壁缓缓倒入红石榴糖浆，让其自然下沉形成渐变。',
      '用橙片和樱桃装饰。饮用前轻轻搅拌。',
    ],
    tips: '红石榴糖浆要最后沿杯壁慢慢倒入，利用密度差自然下沉，才能形成漂亮的日出渐变效果。不要搅拌，先欣赏再喝。',
  },
  {
    id: 'paloma',
    name: '帕洛玛',
    nameEn: 'Paloma',
    baseSpirit: '龙舌兰',
    difficulty: 1,
    abv: 10,
    color: '#fad7a0',
    flavor: '西柚的苦甜与龙舌兰的辛辣，盐边和气泡带来清爽刺激。',
    description: '帕洛玛在墨西哥的受欢迎程度远超玛格丽特。在墨西哥的街头酒吧，调酒师用瓶装西柚汽水直接调制。',
    ingredients: [
      { name: '龙舌兰', amount: '45ml' },
      { name: '新鲜西柚汁', amount: '30ml' },
      { name: '新鲜青柠汁', amount: '15ml' },
      { name: '单糖浆', amount: '10ml' },
      { name: '苏打水', amount: '适量' },
      { name: '盐', amount: '杯边用' },
    ],
    steps: [
      '用青柠汁擦湿杯口，在盐碟中蘸上盐边。',
      '在杯中装满冰块。',
      '倒入龙舌兰、西柚汁、青柠汁和糖浆。',
      '搅拌均匀后注入苏打水至满杯。',
      '用西柚片装饰。',
    ],
    tips: '在墨西哥常用瓶装的Jarritos西柚汽水代替苏打水，风味更正宗。粉红西柚比白西柚甜度更高，更适合调酒。',
  },
  {
    id: 'long-island',
    name: '长岛冰茶',
    nameEn: 'Long Island Iced Tea',
    baseSpirit: '其他',
    difficulty: 3,
    abv: 22,
    color: '#d5a76b',
    flavor: '多种烈酒的复合风味，可乐带来茶色外观和甜蜜口感，极易入口。',
    description: '长岛冰茶以看似冰茶而闻名，实际含有五种烈酒。据说诞生于1970年代纽约长岛的调酒比赛中，是"一杯倒"的代名词。',
    ingredients: [
      { name: '伏特加', amount: '15ml' },
      { name: '金酒', amount: '15ml' },
      { name: '白朗姆酒', amount: '15ml' },
      { name: '龙舌兰', amount: '15ml' },
      { name: '君度利口酒', amount: '15ml' },
      { name: '新鲜柠檬汁', amount: '25ml' },
      { name: '单糖浆', amount: '15ml' },
      { name: '可乐', amount: '少许' },
    ],
    steps: [
      '将除可乐外的所有材料倒入雪克杯。',
      '加入冰块，用力摇晃10-12秒。',
      '滤入装满冰块的高球杯中。',
      '加入少许可乐调出茶色。',
      '轻轻搅拌，用柠檬片装饰。',
    ],
    tips: '虽然喝起来像冰茶，但酒精含量非常高，请注意适量饮用。可乐只加少许调整颜色，加太多会影响口感。',
  },
  {
    id: 'whiskey-iced-tea',
    name: '威士忌冰茶',
    nameEn: 'Whiskey Iced Tea',
    baseSpirit: '其他',
    difficulty: 1,
    abv: 8,
    color: '#c0894e',
    flavor: '冰茶的清爽与威士忌的温暖谷物香气，柠檬增添明亮酸度。',
    description: '这是一款轻松休闲的长饮，将美国南方的波本威士忌文化与中国茶文化巧妙结合，非常适合夏日午后的悠闲时光。',
    ingredients: [
      { name: '波本威士忌', amount: '45ml' },
      { name: '冷泡红茶', amount: '120ml' },
      { name: '单糖浆', amount: '15ml' },
      { name: '新鲜柠檬汁', amount: '15ml' },
      { name: '柠檬片', amount: '装饰用' },
    ],
    steps: [
      '在高球杯中装满冰块。',
      '倒入波本威士忌。',
      '加入冷泡红茶、糖浆和柠檬汁。',
      '搅拌均匀。',
      '用柠檬片和薄荷枝装饰。',
    ],
    tips: '使用冷泡茶而不是热茶冷却，口感更顺滑无涩感。可以用茉莉花茶或伯爵茶代替红茶，风味各异但都很好。',
  },
  {
    id: 'espresso-martini',
    name: '浓缩咖啡马天尼',
    nameEn: 'Espresso Martini',
    baseSpirit: '其他',
    difficulty: 3,
    abv: 18,
    color: '#3e2723',
    flavor: '浓缩咖啡的浓烈醇苦与咖啡利口酒的甜蜜，顶部绵密泡沫如天鹅绒。',
    description: '浓缩咖啡马天尼由传奇调酒师Dick Bradsell在1980年代的伦敦创作。据说一位模特要求一杯能"唤醒她再搞砸她"的酒。',
    ingredients: [
      { name: '伏特加', amount: '45ml' },
      { name: '咖啡利口酒', amount: '30ml' },
      { name: '浓缩咖啡', amount: '30ml' },
      { name: '单糖浆', amount: '10ml' },
      { name: '咖啡豆', amount: '3颗（装饰）' },
    ],
    steps: [
      '先萃取一份浓缩咖啡，稍微冷却。',
      '将伏特加、咖啡利口酒、浓缩咖啡和糖浆倒入雪克杯。',
      '加入冰块，用力摇晃15-20秒。',
      '双重过滤倒入冰镇的马天尼杯。',
      '在泡沫上放3颗咖啡豆作为装饰。',
    ],
    tips: '摇晃必须足够用力才能产生标志性的绵密泡沫。浓缩咖啡必须是热的萃取后放凉的，冷萃咖啡风味不够。如果咖啡够浓可以不加糖浆。',
  },
  {
    id: 'amaretto-sour',
    name: '杏仁酸酒',
    nameEn: 'Amaretto Sour',
    baseSpirit: '其他',
    difficulty: 2,
    abv: 12,
    color: '#f5cba7',
    flavor: '杏仁利口酒的甜美坚果香与柠檬的清新酸度，甘甜适口。',
    description: '杏仁酸酒是一款入门友好的鸡尾酒，杏仁利口酒带来的甜美坚果风味让不习惯烈酒的人也能轻松享用。',
    ingredients: [
      { name: '杏仁利口酒', amount: '45ml' },
      { name: '新鲜柠檬汁', amount: '25ml' },
      { name: '单糖浆', amount: '10ml' },
      { name: '蛋清', amount: '可选，1个' },
      { name: '樱桃', amount: '装饰用' },
    ],
    steps: [
      '如使用蛋清，先干摇蛋清10秒。',
      '加入杏仁利口酒、柠檬汁和糖浆。',
      '加入冰块，用力摇晃15秒。',
      '双重过滤倒入古典杯中。',
      '在泡沫上滴苦精画花，用樱桃装饰。',
    ],
    tips: '进阶版可以在配方中加入15ml波本威士忌增加深度。杏仁利口酒首选Disaronno品牌，风味最为经典。',
  },
  {
    id: 'hugo',
    name: '雨果鸡尾酒',
    nameEn: 'Hugo',
    baseSpirit: '其他',
    difficulty: 1,
    abv: 5,
    color: '#d5f5e3',
    flavor: '接骨木花的梦幻芬芳与气泡酒的轻盈，清新淡雅的低酒精选择。',
    description: '雨果鸡尾酒诞生于2005年的意大利南蒂罗尔，由调酒师Roland Gruber创作。它迅速在欧洲走红，成为普罗塞克鸡尾酒中的新星。',
    ingredients: [
      { name: '普罗塞克起泡酒', amount: '120ml' },
      { name: '接骨木花糖浆', amount: '20ml' },
      { name: '苏打水', amount: '20ml' },
      { name: '新鲜薄荷叶', amount: '数片' },
      { name: '青柠片', amount: '装饰用' },
    ],
    steps: [
      '在大肚酒杯中放入薄荷叶。',
      '倒入接骨木花糖浆。',
      '加入冰块。',
      '倒入普罗塞克起泡酒。',
      '注入少许苏打水。',
      '用青柠片和薄荷枝装饰。',
    ],
    tips: '这是一款酒精度极低的鸡尾酒，非常适合不胜酒力的人。接骨木花糖浆是关键材料，可以用IKEA或Monin品牌的。',
  },
];
